import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import classNames from "classnames";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={
        classNames(inter.className, "grid grid-rows-[80px_1fr_8rem] gap-4 h-screen text-white bg-primaryDark max-w-1200 mx-auto w-95vw")
      }>{children}</body>
    </html>
  );
}


